config/routes.rb
Rails.application.routes.draw do
  get "search", to: "search#search"
  root "citizens#index"
  resources :citizens, path: 'municipes', path_names: { new: 'novo', edit: 'editar'}, except: :destroy
  get 'citizens/index'
  get 'citizens/new'
  get 'citizens/create'
  get 'citizens/edit'
  get 'citizens/update'

  get 'addresses/cities', to: 'addresses#cities'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/address.rb
class Address < ApplicationRecord
  validates :zip_code, presence: true
  validates :street, presence: true
  validates :complement, presence: true
  validates :neighborhood, presence: true
  validates :city, presence: true
  validates :state, presence: true

  belongs_to :citizen

  def to_s
    "#{street}, #{address_number.present? ? address_number : 's/n'}, #{complement}, #{city}/#{state}, #{zip_code}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/citizen.rb
class Citizen < ApplicationRecord
  extend Pagy::Searchkick

  validates :full_name, presence: true
  validates :cpf, presence: true, uniqueness: true, cpf: true
  validates :cns, presence: true, uniqueness: true, cns: true
  validates :email, presence: true, uniqueness: true, email: true
  validates :date_of_birth, presence: true, birth_date: true
  validates :phone, presence: true, format: { with: /\A\+[0-9]{2}\s\([0-9]{2}\)\s[0-9]{4,5}-[0-9]{4}\z/, message: 'format is not valid' }
  validates :status, presence: true

  enum :status, { disabled: 0, enabled: 1 }, default: :enabled

  has_one_attached :photo do |attachable|
    attachable.variant :mini, resize_to_limit: [50, 67]
    attachable.variant :thumb, resize_to_limit: [100, 133]
    attachable.variant :profile, resize_to_limit: [354, 472]
  end

  has_one :address
  accepts_nested_attributes_for :address

  searchkick
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def cities
    @target = params[:target]
    @cities = ::BrAddress::State.cities(state_code: params[:state])

    respond_to do |format|
      format.turbo_stream
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/citizens_controller.rb
class CitizensController < ApplicationController
  include Pagy::Backend

  before_action :set_citizen, only: %i[ show edit update ]
  before_action :ensure_frame_response, only: [:new, :edit]

  # GET /citizens or /citizens.json
  def index
    @pagy, @citizens = pagy(Citizen.all, items: 15)
  end

  # GET /citizens/1 or /citizens/1.json
  def show
  end

  # GET /citizens/new
  def new
    @citizen = Citizen.new
    @citizen.build_address
  end

  # GET /citizens/1/edit
  def edit
  end

  # POST /citizens or /citizens.json
  def create
    @citizen = Citizen.new(citizen_params)

    respond_to do |format|
      if @citizen.save
        message = I18n.t('notification.citizen.created')

        # unless Rails.env.test? do
        #   ::NotificationService.new(:email, @citizen.email, message).call
        #   ::NotificationService.new(:sms, @citizen.phone, message).call
        # end

        format.turbo_stream { render turbo_stream: turbo_stream.prepend("citizen-list", partial: 'citizens/citizen', locals: { citizen: @citizen }) }
        format.html { redirect_to action: :index, notice: "Citizen was successfully created." }
        format.json { render :show, status: :created, location: @citizen }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @citizen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /citizens/1 or /citizens/1.json
  def update
    respond_to do |format|
      if @citizen.update(citizen_params)
        message = I18n.t('notification.citizen.updated')

        # unless Rails.env.test? do
        #   ::NotificationService.new(:email, @citizen.email, message).call
        #   ::NotificationService.new(:sms, @citizen.phone, message).call
        # end

        format.turbo_stream { render turbo_stream: turbo_stream.replace("ctz-#{@citizen.id}", partial: "citizens/citizen", locals: { citizen: @citizen }) }
        format.html { redirect_to action: :index, notice: "Citizen was successfully updated." }
        format.json { render :show, status: :ok, location: @citizen }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @citizen.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_citizen
    @citizen = Citizen.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def citizen_params
    params.require(:citizen).permit(
      :full_name, :cpf, :cns, :email, :date_of_birth, :phone, :status, :photo,
      address_attributes: [ :id, :zip_code, :street, :address_number, :complement,
                              :neighborhood, :city, :state, :ibge_code ])
  end

  def ensure_frame_response
    return unless Rails.env.development?

    redirect_to root_path unless turbo_frame_request?
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  include Pagy::Backend

  def search
    @results = Citizen.pagy_search(params[:search])

    @results = Citizen.pagy_search("*") if params[:search].blank?

    @pagy, @citizens = pagy_searchkick(@results, items: 15)

    render turbo_stream:
      turbo_stream.update('citizens',
        partial: 'citizens/citizens',
        locals: { citizens: @citizens, pagy: @pagy })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def date_format(date)
    date&.strftime('%d/%m/%Y')
  end
end

app/helpers/enum_i18n_helper.rb
module EnumI18nHelper

  # Returns an array of the possible key/i18n values for the enum
  def enum_options_for_select(class_name, enum)
    class_name.send(enum.to_s.pluralize).map do |key, _|
      [enum_i18n(class_name, enum, key), key]
    end
  end

  # Returns the i18n version the models current enum key
  def enum_l(model, enum)
    enum_i18n(model, enum, model.send(enum))
  end

  # Returns the i18n string for the enum key
  def enum_i18n(model_name, enum, key)
    I18n.t("activerecord.enums.#{model_name.model_name.i18n_key}.#{enum.to_s.pluralize}.#{key}")
  end
end

app/views/addresses/cities.html.erb
<h1>Addresses#cities</h1>
<p>Find me in app/views/addresses/cities.html.erb</p>

app/views/addresses/cities.turbo_stream.erb
<%= turbo_stream.update @target do %>
  <%= options_for_select(@cities) %>
<% end %>

app/views/citizens/_citizen.html.erb
<tr id="ctz-<%= citizen.id %>">
  <td>
  <% if citizen.photo.attached? %>
    <%= image_tag citizen.photo.variant(:mini) %>
  <% else %>
    <div class="no-photo"><%= "\u{1F464}" %></div>
  <% end %>
  </td>
  <td>
    <strong>
    <%= link_to citizen.full_name, citizen, data: { turbo_frame: 'modal' } %></strong>
  </td>
  <td>
    <%= citizen.cpf %>
  </td>
  <td>
    <%= citizen.cns %>
  </td>
  <td>
    <%= citizen.email %>
  </td>
  <td>
    <%= date_format(citizen.date_of_birth) %>
  </td>
  <td>
    <%= citizen.phone %>
  </td>
  <td>
    <% if citizen.enabled? %>
    <%= "\u{1F7E2}" %>
    <% else %>
    <%= "\u{1F534}" %>
    <% end %>
    <%= enum_i18n(Citizen, :status, citizen.status) %>
  </td>
  <td>
    <%= link_to "Editar", edit_citizen_path(citizen), data: { turbo_frame: 'modal' } %>
  </td>
</tr>

app/views/citizens/_citizens.html.erb
<table>
      <thead>
        <tr>
          <th></th>
           <th>NOME</th>
           <th>CPF</th>
           <th>CNS</th>
           <th>EMAIL</th>
           <th>DATA NASCIMENTO</th>
           <th>TELEFONE</th>
           <th colspan="1">SITUAÇ&Atilde;O</th>
           <th></th>
        </tr>
      </thead>
      <tbody id="citizen-list">
        <% citizens.each do |citizen| %>
          <%= render citizen %>
        <% end %>
      </tbody>
      <tfoot>
        <% if pagy.pages > 1 %>
        <tr>
          <td colspan="9">
            <%== pagy_nav(pagy) %>
          </td>
        </tr>
        <% end %>
      </tfoot>
    </table>

app/views/citizens/_form.html.erb
<div class="modal-content">
<%= form_with(model: citizen) do |form| %>
  <% if citizen.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(citizen.errors.count, "error") %> prohibited this citizen from being saved:</h2>

      <ul>
        <% citizen.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="modal-section">Dados Pessoais</div>
  <div class="form-row">
    <%= form.label :full_name do %><span>Nome</span>
      <%= form.text_field :full_name, class: 'input-xlarge' %>
    <% end %>
    <%= form.label :email do %><span>Email</span>
      <%= form.text_field :email, class: 'input-large' %>
    <% end %>
  </div>

  <div class="form-row">
    <%= form.label :cpf do %><span>CPF</span>
      <%= form.text_field :cpf, class: 'input-medium', placeholder: '999.999.999-99' %>
    <% end %>
    <%= form.label :cns do %><span>CNS</span>
      <%= form.text_field :cns, class: 'input-medium', placeholder: '999 9999 9999 9999' %>
    <% end %>
    <%= form.label :date_of_birth do %><span>Data Nascimento</span>
      <%= form.date_field :date_of_birth, class: 'input-medium' %>
    <% end %>
  </div>
  <div class="form-row">
    <%= form.label :phone do %><span>Telefone</span>
      <%= form.text_field :phone, class: 'input-medium', placeholder: '+99 (99) 99999-9999' %>
    <% end %>
    <%= form.label :status do %><span>Situa&ccedil;&atilde;o</span>
      <%= form.select :status, enum_options_for_select(Citizen, :status) %>
    <% end %>
    <%= form.label :photo do %><span>Foto</span>
      <%= form.file_field :photo %>
    <% end %>
  </div>
  <div class="modal-section">Endere&ccedil;o</div>
  <%= form.fields_for :address do |address_form| %>
    <div class="form-row">
      <%= address_form.label :street do %><span>Logradouro</span>
        <%= address_form.text_field :street, class: 'input-xlarge' %>
      <% end %>
      <%= address_form.label :address_number do %><span>N°</span>
        <%= address_form.text_field :address_number, class: 'input-small' %>
      <% end %>
      <%= address_form.label :neighborhood do %><span>Bairro</span>
        <%= address_form.text_field :neighborhood, class: 'input-medium' %>
      <% end %>
    </div>
    <div
      data-controller="select"
      data-select-url-value="<%= addresses_cities_path %>"
      data-select-param-value="state"
      class="form-row">
      <%= address_form.label :state do %><span>UF</span>
        <%= address_form.select :state, ::BrAddress::State.all.invert, { prompt: 'Selecione um estado'} , data: { class: 'input-small',
                                                                                                                  action: "change->select#change",
                                                                                                                  select_target: "state"  }  %>
      <% end %>
      <%= address_form.label :city do %><span>Cidade</span>
        <%= address_form.select :city, [], {}, data: { id: nil, class: 'input-large', select_target: "select" } %>
      <% end %>
      <%= address_form.label :zip_code do %><span>Cep</span>
        <%= address_form.text_field :zip_code, class: 'input-zipcode', placeholder: '99999-999'  %>
      <% end %>
    </div>
    <div class="form-row">
      <%= address_form.label :complement do %><span>Complemento</span>
        <%= address_form.text_field :complement, class: 'input-xlarge' %>
      <% end %>
      <%= address_form.label :ibge_code do %><span>C&oacute;digo IBGE</span>
        <%= address_form.text_field :ibge_code, class: 'input-large' %>
      <% end %>
    </div>
  <% end %>
  <br />
  <div class="form-button-actions">
    <%= button_tag "Cancelar", data: { action: "turbo-modal#hideModal" }, type: "button", class: "form-bt-cancel" %>
    <%= form.submit "Salvar", class: "form-bt-save" %>
  </div>
<% end %>
</div>

app/views/citizens/_show_citizen.html.erb
<div class="show-citizen">
  <div>
    <% if citizen.photo.attached? %>
      <%= image_tag citizen.photo.variant(:profile) %>
    <% else %>
      <div class="no-photo"><%= "\u{1F464}" %></div>
    <% end %>
  </div>
  <div>
    <p>
      <strong>Nome:</strong> <%= citizen.full_name %>
    </p>
    <p>
      <strong>CPF:</strong> <%= citizen.cpf %>
    </p>
    <p>
      <strong>CNS:</strong> <%= citizen.cns %>
    </p>
    <p>
      <strong>Email:</strong> <%= citizen.email %>
    </p>
    <p>
      <strong>Data Nascimento:</strong> <%= date_format(citizen.date_of_birth) %>
    </p>
    <p>
      <strong>Telefone:</strong> <%= citizen.phone %>
    </p>
    <p>
      <strong>Situa&ccedil;&atilde;o:</strong> <%= enum_i18n(Citizen, :status, citizen.status) %>
    </p>
    <p>
      <strong>Endere&ccedil;o:</strong> <%= citizen.address.to_s %>
    </p>

    <p>
      <%= link_to "Editar", edit_citizen_path(citizen), data: { turbo_frame: 'modal' } %>
    </p>
  </div>
</div>

app/views/citizens/edit.html.erb
<%= render TurboModalComponent.new(title: "Edit citizen") do %>
  <%= render "form", citizen: @citizen  %>
<% end %>

app/views/citizens/index.html.erb
<header>
  <span>
    <h1>Munic&iacute;pes</h1>
  </span>
  <span>
    <%= form_with url: search_path, method: :get do |form| %>
      <%= form.label('Pesquisar') %>
      <%= form.text_field(:search) %>
      <%= form.submit "Buscar" %>
    <% end %>
  </span>
</header>
<main>
  <div class="citizen-info">
    <span>
      <%= button_to '+ Novo municípe', new_citizen_path, method: :get, data: { turbo_frame: 'modal' } %>
    </span>
  </div>
  <div id="citizens">
  <%= render "citizens", citizens: @citizens, pagy: @pagy %>
  </div>
</main>

app/views/citizens/new.html.erb
<%= render TurboModalComponent.new(title: "New citizen!") do %>
  <%= render "form", citizen: @citizen  %>
<% end %>

app/views/citizens/show.html.erb
<%= render TurboModalComponent.new(title: "Show citizen!") do %>
  <%= render "show_citizen", citizen: @citizen  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pubman</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= turbo_frame_tag "modal" %>
    <div id="container">
      <%= yield %>
      <footer></footer>
    </div>
  </body>
</html>